name: TokyPaper-Test-Plugin
version: ${version}
main: io.toky.tokypaper.testplugin.TestPlugin
description: TokyPaper Test Plugin
author: Denery
api-version: 1.19
load: STARTUP
bootstrapper: io.toky.tokypaper.testplugin.TestPluginBootstrap
defaultPerm: FALSE
